//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HbysEntities : DbContext
    {
        public HbysEntities() : base("name=HbysEntities")
        {
           /* Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;*/
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PER_ADAY_DRM_TNM> PER_ADAY_DRM_TNM { get; set; }
        public virtual DbSet<PER_AILE> PER_AILE { get; set; }
        public virtual DbSet<PER_AILE_SGLK_MLZ> PER_AILE_SGLK_MLZ { get; set; }
        public virtual DbSet<PER_BRANS_TNM> PER_BRANS_TNM { get; set; }
        public virtual DbSet<PER_CEZA> PER_CEZA { get; set; }
        public virtual DbSet<PER_CEZA_TNM> PER_CEZA_TNM { get; set; }
        public virtual DbSet<PER_CLS_BCM_TNM> PER_CLS_BCM_TNM { get; set; }
        public virtual DbSet<PER_DIL_SNV> PER_DIL_SNV { get; set; }
        public virtual DbSet<PER_DIL_TNM> PER_DIL_TNM { get; set; }
        public virtual DbSet<PER_EHLIYET> PER_EHLIYET { get; set; }
        public virtual DbSet<PER_EHLIYET_TNM> PER_EHLIYET_TNM { get; set; }
        public virtual DbSet<PER_HRK> PER_HRK { get; set; }
        public virtual DbSet<PER_IL_TNM> PER_IL_TNM { get; set; }
        public virtual DbSet<PER_ILCE_TNM> PER_ILCE_TNM { get; set; }
        public virtual DbSet<PER_ISTIFA> PER_ISTIFA { get; set; }
        public virtual DbSet<PER_IZIN> PER_IZIN { get; set; }
        public virtual DbSet<PER_IZIN_TNM> PER_IZIN_TNM { get; set; }
        public virtual DbSet<PER_KAN_ISTM_FRM> PER_KAN_ISTM_FRM { get; set; }
        public virtual DbSet<PER_KAN_ISTM_FRM_TUR> PER_KAN_ISTM_FRM_TUR { get; set; }
        public virtual DbSet<PER_KAN_ISTM_TUR_TNM> PER_KAN_ISTM_TUR_TNM { get; set; }
        public virtual DbSet<PER_KARTLAR> PER_KARTLAR { get; set; }
        public virtual DbSet<PER_KIMLIK> PER_KIMLIK { get; set; }
        public virtual DbSet<PER_KRM_BKNLK_TNM> PER_KRM_BKNLK_TNM { get; set; }
        public virtual DbSet<PER_KRM_BRM_KDR_TNM> PER_KRM_BRM_KDR_TNM { get; set; }
        public virtual DbSet<PER_KRM_BRM_KDR_YER> PER_KRM_BRM_KDR_YER { get; set; }
        public virtual DbSet<PER_KRM_BRM_TNM> PER_KRM_BRM_TNM { get; set; }
        public virtual DbSet<PER_KRM_TNM> PER_KRM_TNM { get; set; }
        public virtual DbSet<PER_KURS> PER_KURS { get; set; }
        public virtual DbSet<PER_KURS_TNM> PER_KURS_TNM { get; set; }
        public virtual DbSet<PER_MCBR_HZMT_DRM_TNM> PER_MCBR_HZMT_DRM_TNM { get; set; }
        public virtual DbSet<PER_MSLK_FLYT> PER_MSLK_FLYT { get; set; }
        public virtual DbSet<PER_MSLK_FLYT_DETAY_TNM> PER_MSLK_FLYT_DETAY_TNM { get; set; }
        public virtual DbSet<PER_MSLK_FLYT_TNM> PER_MSLK_FLYT_TNM { get; set; }
        public virtual DbSet<PER_MSLK_FLYT_TUR_TNM> PER_MSLK_FLYT_TUR_TNM { get; set; }
        public virtual DbSet<PER_MUAYENE> PER_MUAYENE { get; set; }
        public virtual DbSet<PER_NBT_TNM> PER_NBT_TNM { get; set; }
        public virtual DbSet<PER_NBT_VRD> PER_NBT_VRD { get; set; }
        public virtual DbSet<PER_NBT_VRD_PER> PER_NBT_VRD_PER { get; set; }
        public virtual DbSet<PER_NBT_VRD_TNM> PER_NBT_VRD_TNM { get; set; }
        public virtual DbSet<PER_ODUL> PER_ODUL { get; set; }
        public virtual DbSet<PER_ODUL_TNM> PER_ODUL_TNM { get; set; }
        public virtual DbSet<PER_OKUL> PER_OKUL { get; set; }
        public virtual DbSet<PER_OKUL_FKLT_BLM_TNM> PER_OKUL_FKLT_BLM_TNM { get; set; }
        public virtual DbSet<PER_OKUL_FKLT_BLM_TUR_TNM> PER_OKUL_FKLT_BLM_TUR_TNM { get; set; }
        public virtual DbSet<PER_OKUL_FKLT_TNM> PER_OKUL_FKLT_TNM { get; set; }
        public virtual DbSet<PER_OKUL_FKLT_TUR_TNM> PER_OKUL_FKLT_TUR_TNM { get; set; }
        public virtual DbSet<PER_OKUL_TNM> PER_OKUL_TNM { get; set; }
        public virtual DbSet<PER_OKUL_TUR_TNM> PER_OKUL_TUR_TNM { get; set; }
        public virtual DbSet<PER_OZEL_MUAYENE> PER_OZEL_MUAYENE { get; set; }
        public virtual DbSet<PER_RESIM> PER_RESIM { get; set; }
        public virtual DbSet<PER_SAKAT_TNM> PER_SAKAT_TNM { get; set; }
        public virtual DbSet<PER_SGLK> PER_SGLK { get; set; }
        public virtual DbSet<PER_SGLK_MLZ> PER_SGLK_MLZ { get; set; }
        public virtual DbSet<PER_SGLK_MLZ_TNM> PER_SGLK_MLZ_TNM { get; set; }
        public virtual DbSet<PER_SGLK_TRM> PER_SGLK_TRM { get; set; }
        public virtual DbSet<PER_SNF_TNM> PER_SNF_TNM { get; set; }
        public virtual DbSet<PER_SNV_TNM> PER_SNV_TNM { get; set; }
        public virtual DbSet<PER_STAJ_DRM_TNM> PER_STAJ_DRM_TNM { get; set; }
        public virtual DbSet<PER_TSKLT_TNM> PER_TSKLT_TNM { get; set; }
        public virtual DbSet<PER_ULKE_TNM> PER_ULKE_TNM { get; set; }
        public virtual DbSet<PER_UNVAN_TNM> PER_UNVAN_TNM { get; set; }
        public virtual DbSet<PER_GCC_GRV> PER_GCC_GRV { get; set; }
        public virtual DbSet<PER_GRV> PER_GRV { get; set; }
        public virtual DbSet<PER_IZIN_ISTEK> PER_IZIN_ISTEK { get; set; }
        public virtual DbSet<PER_KART_KURUM> PER_KART_KURUM { get; set; }
        public virtual DbSet<PER_KART_LOG> PER_KART_LOG { get; set; }
    }
}
