//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_IZIN_TNM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PER_IZIN_TNM()
        {
            this.PER_IZIN = new HashSet<PER_IZIN>();
        }
    
        public string IZIN_KODU { get; set; }
        public string IZIN_ADI { get; set; }
        public string UCRETSIZ_EH { get; set; }
        public string PLN_EH { get; set; }
        public string IZIN_TURU { get; set; }
        public Nullable<int> IZIN_SURE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_IZIN> PER_IZIN { get; set; }
    }
}
