//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_KRM_TNM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PER_KRM_TNM()
        {
            this.PER_KRM_BRM_TNM = new HashSet<PER_KRM_BRM_TNM>();
            this.PER_NBT_TNM = new HashSet<PER_NBT_TNM>();
        }
    
        public int KRM_KODU { get; set; }
        public string KRM_ADI { get; set; }
        public string KAMU_OZEL { get; set; }
        public string TLF { get; set; }
        public string FAKS { get; set; }
        public string ADR { get; set; }
        public Nullable<int> BKNLK_KODU { get; set; }
        public byte[] LOGO { get; set; }
        public string IZIN_RPR_MKM_ADI { get; set; }
    
        public virtual PER_KRM_BKNLK_TNM PER_KRM_BKNLK_TNM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_KRM_BRM_TNM> PER_KRM_BRM_TNM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_NBT_TNM> PER_NBT_TNM { get; set; }
    }
}
