//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_EHLIYET
    {
        public int PER_ID { get; set; }
        public string EHLIYET_KODU { get; set; }
        public Nullable<System.DateTime> BELGE_TRH { get; set; }
        public string BELGE_NO { get; set; }
        public int PEHID { get; set; }
    
        public virtual PER_EHLIYET_TNM PER_EHLIYET_TNM { get; set; }
        public virtual PER_EHLIYET_TNM PER_EHLIYET_TNM1 { get; set; }
        public virtual PER_KIMLIK PER_KIMLIK { get; set; }
        public virtual PER_KIMLIK PER_KIMLIK1 { get; set; }
    }
}
