//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_MSLK_FLYT
    {
        public int MSLK_FLYT_ID { get; set; }
        public int PER_ID { get; set; }
        public int MSLK_FLYT_TUR_KODU { get; set; }
        public int MSLK_FLYT_KODU { get; set; }
        public Nullable<int> MSLK_FLYT_DETAY_KODU { get; set; }
        public Nullable<System.DateTime> GCR_TRH { get; set; }
        public Nullable<int> ISIM_SIRA_NO { get; set; }
        public string ATIF_EH { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> PUAN { get; set; }
    
        public virtual PER_KIMLIK PER_KIMLIK { get; set; }
        public virtual PER_MSLK_FLYT_DETAY_TNM PER_MSLK_FLYT_DETAY_TNM { get; set; }
        public virtual PER_MSLK_FLYT_TNM PER_MSLK_FLYT_TNM { get; set; }
        public virtual PER_MSLK_FLYT_TUR_TNM PER_MSLK_FLYT_TUR_TNM { get; set; }
    }
}
