//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_KARTLAR
    {
        public int KARTID { get; set; }
        public int PERID { get; set; }
        public Nullable<int> KARTTURU { get; set; }
        public string GOREVI { get; set; }
        public string BIRIMI { get; set; }
        public Nullable<int> VERILIS_NEDEN { get; set; }
        public Nullable<System.DateTime> VERILIS_TARIH { get; set; }
        public Nullable<int> KULID { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
