//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_GRV
    {
        public int GRV_ID { get; set; }
        public int ASIL_PER_ID { get; set; }
        public Nullable<int> YEDEK_PER_ID { get; set; }
        public string GRV_ADI { get; set; }
        public System.DateTime BSL_TRH { get; set; }
        public System.DateTime BTS_TRH { get; set; }
        public Nullable<int> EKLEYEN_KULID { get; set; }
        public System.DateTime KAYIT_TRH { get; set; }
    }
}
