//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_OKUL_TNM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PER_OKUL_TNM()
        {
            this.PER_OKUL = new HashSet<PER_OKUL>();
        }
    
        public int OKUL_KODU { get; set; }
        public string OKUL_ADI { get; set; }
        public string OKUL_TUR_KODU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_OKUL> PER_OKUL { get; set; }
        public virtual PER_OKUL_TUR_TNM PER_OKUL_TUR_TNM { get; set; }
    }
}
