//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_IZIN_ISTEK
    {
        public int ISTEK_ID { get; set; }
        public int PER_ID { get; set; }
        public string IZIN_KODU { get; set; }
        public System.DateTime IZIN_BSL_TRH { get; set; }
        public System.DateTime IZIN_BTS_TRH { get; set; }
        public string ADRES { get; set; }
        public string ACIKLAMA { get; set; }
        public System.DateTime IZIN_ISTEK_TRH { get; set; }
        public Nullable<int> KULID { get; set; }
        public Nullable<int> ISLEMYAPANKULID { get; set; }
        public Nullable<System.DateTime> ISLEMYAPANTRH { get; set; }
    }
}
