//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_SGLK_TRM
    {
        public int TRM_ID { get; set; }
        public int PER_ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string AKCIGER_GRAFISI { get; set; }
        public string PPD { get; set; }
        public string BOGAZ { get; set; }
        public string BURUN { get; set; }
        public string GAITA { get; set; }
        public string GAITA_PARAZIT { get; set; }
        public string ANTI_HIV { get; set; }
        public string ANTI_HCV { get; set; }
        public string HBS_AG { get; set; }
        public string HBS_AB { get; set; }
        public string DIGER { get; set; }
        public string DEGERLENDIRME { get; set; }
        public Nullable<int> DRID { get; set; }
        public string DRADSOYAD { get; set; }
        public Nullable<int> KULID { get; set; }
        public Nullable<System.DateTime> ISLEMTAR { get; set; }
        public bool AKTIF { get; set; }
    }
}
