//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_SGLK
    {
        public int PER_ID { get; set; }
        public string KRONIK { get; set; }
        public string DEVAMLI_ILAC { get; set; }
        public string LATEX { get; set; }
        public string SIGARA { get; set; }
        public Nullable<int> BOY { get; set; }
        public Nullable<int> KILO { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> KULID { get; set; }
    }
}
