//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_NBT_VRD_TNM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PER_NBT_VRD_TNM()
        {
            this.PER_NBT_VRD = new HashSet<PER_NBT_VRD>();
            this.PER_KIMLIK = new HashSet<PER_KIMLIK>();
        }
    
        public int NBT_NO { get; set; }
        public int VRD_NO { get; set; }
        public string BSL_SAAT { get; set; }
        public string BTS_SAAT { get; set; }
        public decimal SURE { get; set; }
        public string SURE_KODU { get; set; }
        public string DRM_KODU { get; set; }
        public int PER_MKTR { get; set; }
        public string ACIL_KODU { get; set; }
    
        public virtual PER_NBT_TNM PER_NBT_TNM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_NBT_VRD> PER_NBT_VRD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_KIMLIK> PER_KIMLIK { get; set; }
    }
}
