//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_NBT_VRD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PER_NBT_VRD()
        {
            this.PER_NBT_VRD_PER = new HashSet<PER_NBT_VRD_PER>();
        }
    
        public int VRD_NO { get; set; }
        public decimal YIL { get; set; }
        public string AY { get; set; }
        public string ONAY_EH { get; set; }
        public Nullable<System.DateTime> ONAY_TRH { get; set; }
    
        public virtual PER_NBT_VRD_TNM PER_NBT_VRD_TNM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_NBT_VRD_PER> PER_NBT_VRD_PER { get; set; }
    }
}
