//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_CEZA
    {
        public int PER_ID { get; set; }
        public int CEZA_KODU { get; set; }
        public System.DateTime CEZA_TRH { get; set; }
        public int CEZA_ID { get; set; }
    
        public virtual PER_CEZA_TNM PER_CEZA_TNM { get; set; }
        public virtual PER_KIMLIK PER_KIMLIK { get; set; }
    }
}
