//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_KURS
    {
        public int PER_ID { get; set; }
        public int KURS_KODU { get; set; }
        public System.DateTime KURS_BSL_TRH { get; set; }
        public Nullable<System.DateTime> KURS_BTS_TRH { get; set; }
        public string DRC_KODU { get; set; }
        public Nullable<int> SIRA_NO { get; set; }
        public string KURS_KRM_ADI { get; set; }
        public int KURS_ID { get; set; }
    
        public virtual PER_KIMLIK PER_KIMLIK { get; set; }
        public virtual PER_KURS_TNM PER_KURS_TNM { get; set; }
    }
}
