//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_CLS_BCM_TNM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PER_CLS_BCM_TNM()
        {
            this.PER_KRM_BRM_KDR_YER = new HashSet<PER_KRM_BRM_KDR_YER>();
            this.PER_KIMLIK = new HashSet<PER_KIMLIK>();
        }
    
        public string CLS_BCM_KODU { get; set; }
        public string CLS_BCM_ADI { get; set; }
        public byte CLS_DRM_KODU { get; set; }
        public Nullable<int> SIRA_NO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_KRM_BRM_KDR_YER> PER_KRM_BRM_KDR_YER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_KIMLIK> PER_KIMLIK { get; set; }
    }
}
