//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_SGLK_MLZ_TNM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PER_SGLK_MLZ_TNM()
        {
            this.PER_AILE_SGLK_MLZ = new HashSet<PER_AILE_SGLK_MLZ>();
            this.PER_AILE_SGLK_MLZ1 = new HashSet<PER_AILE_SGLK_MLZ>();
            this.PER_SGLK_MLZ = new HashSet<PER_SGLK_MLZ>();
        }
    
        public int MLZ_KODU { get; set; }
        public string MLZ_ADI { get; set; }
        public int SURE { get; set; }
        public string SURE_KODU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_AILE_SGLK_MLZ> PER_AILE_SGLK_MLZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_AILE_SGLK_MLZ> PER_AILE_SGLK_MLZ1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_SGLK_MLZ> PER_SGLK_MLZ { get; set; }
    }
}
