//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_AILE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PER_AILE()
        {
            this.PER_AILE_SGLK_MLZ = new HashSet<PER_AILE_SGLK_MLZ>();
            this.PER_AILE_SGLK_MLZ1 = new HashSet<PER_AILE_SGLK_MLZ>();
        }
    
        public int PER_ID { get; set; }
        public string YKN_TCKIMLIK_NO { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string YKN_KODU { get; set; }
        public string OKUL_TUR_KODU { get; set; }
        public Nullable<System.DateTime> DGM_TRH { get; set; }
        public Nullable<System.DateTime> OLM_TRH { get; set; }
        public string CINS_KODU { get; set; }
        public string SAKAT_DRC_KODU { get; set; }
        public string ACIKLAMA { get; set; }
        public string BKM_YKM_EH { get; set; }
        public Nullable<int> SAKAT_KODU { get; set; }
        public int YKN_PER_ID { get; set; }
        public string ONCEKI_SOYADI { get; set; }
        public string MDN_HAL_KODU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_AILE_SGLK_MLZ> PER_AILE_SGLK_MLZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_AILE_SGLK_MLZ> PER_AILE_SGLK_MLZ1 { get; set; }
        public virtual PER_OKUL_TUR_TNM PER_OKUL_TUR_TNM { get; set; }
        public virtual PER_OKUL_TUR_TNM PER_OKUL_TUR_TNM1 { get; set; }
        public virtual PER_KIMLIK PER_KIMLIK { get; set; }
        public virtual PER_KIMLIK PER_KIMLIK1 { get; set; }
        public virtual PER_SAKAT_TNM PER_SAKAT_TNM { get; set; }
        public virtual PER_SAKAT_TNM PER_SAKAT_TNM1 { get; set; }
    }
}
