//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_KRM_BRM_KDR_YER
    {
        public int PER_ID { get; set; }
        public int KRM_BRM_KDR_KODU { get; set; }
        public System.DateTime GRV_BSL_TRH { get; set; }
        public Nullable<System.DateTime> GRV_BTS_TRH { get; set; }
        public string CLS_BCM_KODU { get; set; }
        public string ACIKLAMA { get; set; }
        public string DRM_KODU { get; set; }
    
        public virtual PER_CLS_BCM_TNM PER_CLS_BCM_TNM { get; set; }
        public virtual PER_KIMLIK PER_KIMLIK { get; set; }
        public virtual PER_KRM_BRM_KDR_TNM PER_KRM_BRM_KDR_TNM { get; set; }
    }
}
