//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_IZIN
    {
        public int PER_ID { get; set; }
        public string IZIN_KODU { get; set; }
        public System.DateTime IZIN_BSL_TRH { get; set; }
        public System.DateTime IZIN_BTS_TRH { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> KLN_IZIN1 { get; set; }
        public Nullable<int> KLN_IZIN2 { get; set; }
        public string ADRES { get; set; }
        public string YERINE { get; set; }
        public Nullable<int> YOL_SURE { get; set; }
        public Nullable<System.DateTime> GRV_BSL_TRH { get; set; }
        public string HZMT_SURE { get; set; }
        public Nullable<System.DateTime> IZIN_ISTEK_TRH { get; set; }
        public string IZIN_KAYIT_NO { get; set; }
        public string BRM_AMIRI { get; set; }
        public string BRM_AMIRI_UNVAN { get; set; }
        public string BASHEKIM { get; set; }
        public string BASHEKIM_YER { get; set; }
        public string BASHEKIM_UNVAN { get; set; }
        public string SGLK_BSK { get; set; }
        public string SGLK_BSK_YER { get; set; }
        public string SGLK_BSK_UNVAN { get; set; }
        public string KAYMAKAM { get; set; }
        public string KAYMAKAM_UNVAN { get; set; }
        public Nullable<int> DAKIKA_IZIN { get; set; }
        public string GNL_ACIKLAMA { get; set; }
        public string DUZENLEYEN { get; set; }
        public string DUZENLEYEN_UNVAN { get; set; }
        public int IZINID { get; set; }
    
        public virtual PER_IZIN_TNM PER_IZIN_TNM { get; set; }
        public virtual PER_KIMLIK PER_KIMLIK { get; set; }
    }
}
