//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_KIMLIK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PER_KIMLIK()
        {
            this.PER_AILE = new HashSet<PER_AILE>();
            this.PER_AILE1 = new HashSet<PER_AILE>();
            this.PER_CEZA = new HashSet<PER_CEZA>();
            this.PER_DIL_SNV = new HashSet<PER_DIL_SNV>();
            this.PER_EHLIYET = new HashSet<PER_EHLIYET>();
            this.PER_EHLIYET1 = new HashSet<PER_EHLIYET>();
            this.PER_HRK = new HashSet<PER_HRK>();
            this.PER_ISTIFA = new HashSet<PER_ISTIFA>();
            this.PER_IZIN = new HashSet<PER_IZIN>();
            this.PER_KAN_ISTM_FRM = new HashSet<PER_KAN_ISTM_FRM>();
            this.PER_KRM_BRM_KDR_YER = new HashSet<PER_KRM_BRM_KDR_YER>();
            this.PER_KURS = new HashSet<PER_KURS>();
            this.PER_MSLK_FLYT = new HashSet<PER_MSLK_FLYT>();
            this.PER_MUAYENE = new HashSet<PER_MUAYENE>();
            this.PER_MUAYENE1 = new HashSet<PER_MUAYENE>();
            this.PER_MUAYENE2 = new HashSet<PER_MUAYENE>();
            this.PER_NBT_VRD_PER = new HashSet<PER_NBT_VRD_PER>();
            this.PER_NBT_VRD_PER1 = new HashSet<PER_NBT_VRD_PER>();
            this.PER_ODUL = new HashSet<PER_ODUL>();
            this.PER_OKUL = new HashSet<PER_OKUL>();
            this.PER_OZEL_MUAYENE = new HashSet<PER_OZEL_MUAYENE>();
            this.PER_SGLK_MLZ = new HashSet<PER_SGLK_MLZ>();
            this.PER_GCC_GRV = new HashSet<PER_GCC_GRV>();
            this.PER_NBT_VRD_TNM = new HashSet<PER_NBT_VRD_TNM>();
        }
    
        public string TCKIMLIK_NO { get; set; }
        public string EMSAN_NO { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string BABA_ADI { get; set; }
        public string ANA_ADI { get; set; }
        public string ONCEKI_SOYADI { get; set; }
        public string DRM_KODU { get; set; }
        public Nullable<System.DateTime> DGM_TRH { get; set; }
        public Nullable<int> SNF_KODU { get; set; }
        public Nullable<int> UNVAN_KODU { get; set; }
        public Nullable<int> BRANS_KODU { get; set; }
        public string ADAY_DRM_KODU { get; set; }
        public string MCBR_HZMT_DRM_KODU { get; set; }
        public string STAJ_DRM_KODU { get; set; }
        public Nullable<System.DateTime> MCBR_HZMT_BTS_TRH { get; set; }
        public Nullable<System.DateTime> STAJ_BTS_TRH { get; set; }
        public Nullable<System.DateTime> MMR_BSL_TRH { get; set; }
        public string TSKLT_KODU { get; set; }
        public int PER_ID { get; set; }
        public string CINS_KODU { get; set; }
        public string NFS_CZD_SERI { get; set; }
        public string NFS_CZD_NO { get; set; }
        public string MDN_HAL_KODU { get; set; }
        public string DINI { get; set; }
        public string ULKE_KODU { get; set; }
        public string KAN_GRP_KODU { get; set; }
        public Nullable<int> NFS_KYT_IL_KODU { get; set; }
        public Nullable<int> NFS_KYT_ILCE_KODU { get; set; }
        public string NFS_KYT_KOY_MAH { get; set; }
        public string NFS_KYT_CILT_NO { get; set; }
        public string NFS_KYT_AILE_SIRA_NO { get; set; }
        public string NFS_KYT_SIRA_NO { get; set; }
        public string NFS_CZD_VRN_YER { get; set; }
        public string NFS_CZD_VRL_NDN { get; set; }
        public Nullable<System.DateTime> NFS_CZD_VRL_TRH { get; set; }
        public string NFS_CZD_KYT_NO { get; set; }
        public string DGM_YERI { get; set; }
        public string ADR_DAIMI { get; set; }
        public string ADR_IS { get; set; }
        public string TLF_EV { get; set; }
        public string TLF_IS { get; set; }
        public string TLF_CEP { get; set; }
        public string ADR_EV { get; set; }
        public string VERGI_NO { get; set; }
        public string KRM_SCL_NO { get; set; }
        public Nullable<System.DateTime> ASKR_DNS_TRH { get; set; }
        public Nullable<System.DateTime> ASKR_GDS_TRH { get; set; }
        public string ASKR_DRM_KODU { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> KRM_BRM_KODU { get; set; }
        public Nullable<int> KRM_BRM_KDR_KODU { get; set; }
        public Nullable<int> KDM_YILI { get; set; }
        public Nullable<int> KDR_DRC { get; set; }
        public Nullable<int> KDR_KDM { get; set; }
        public Nullable<int> PER_SIRA_NO { get; set; }
        public Nullable<int> SAKAT_KODU { get; set; }
        public string SAKAT_DRC_KODU { get; set; }
        public Nullable<System.DateTime> KTL_TRH { get; set; }
        public Nullable<System.DateTime> AYR_TRH { get; set; }
        public string EPOSTA { get; set; }
        public Nullable<short> SEND_ID { get; set; }
        public string HASTALIK_BAGISIKLIK { get; set; }
        public Nullable<decimal> PDKS_KIMLIK { get; set; }
        public Nullable<decimal> PDKS_KART_NO { get; set; }
        public string PDKS_SIFRE { get; set; }
        public string TLF_DAHILI { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        public virtual PER_ADAY_DRM_TNM PER_ADAY_DRM_TNM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_AILE> PER_AILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_AILE> PER_AILE1 { get; set; }
        public virtual PER_BRANS_TNM PER_BRANS_TNM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_CEZA> PER_CEZA { get; set; }
        public virtual PER_CLS_BCM_TNM PER_CLS_BCM_TNM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_DIL_SNV> PER_DIL_SNV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_EHLIYET> PER_EHLIYET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_EHLIYET> PER_EHLIYET1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_HRK> PER_HRK { get; set; }
        public virtual PER_IL_TNM PER_IL_TNM { get; set; }
        public virtual PER_ILCE_TNM PER_ILCE_TNM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_ISTIFA> PER_ISTIFA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_IZIN> PER_IZIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_KAN_ISTM_FRM> PER_KAN_ISTM_FRM { get; set; }
        public virtual PER_MCBR_HZMT_DRM_TNM PER_MCBR_HZMT_DRM_TNM { get; set; }
        public virtual PER_SNF_TNM PER_SNF_TNM { get; set; }
        public virtual PER_STAJ_DRM_TNM PER_STAJ_DRM_TNM { get; set; }
        public virtual PER_TSKLT_TNM PER_TSKLT_TNM { get; set; }
        public virtual PER_ULKE_TNM PER_ULKE_TNM { get; set; }
        public virtual PER_UNVAN_TNM PER_UNVAN_TNM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_KRM_BRM_KDR_YER> PER_KRM_BRM_KDR_YER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_KURS> PER_KURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_MSLK_FLYT> PER_MSLK_FLYT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_MUAYENE> PER_MUAYENE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_MUAYENE> PER_MUAYENE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_MUAYENE> PER_MUAYENE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_NBT_VRD_PER> PER_NBT_VRD_PER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_NBT_VRD_PER> PER_NBT_VRD_PER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_ODUL> PER_ODUL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_OKUL> PER_OKUL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_OZEL_MUAYENE> PER_OZEL_MUAYENE { get; set; }
        public virtual PER_RESIM PER_RESIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_SGLK_MLZ> PER_SGLK_MLZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_GCC_GRV> PER_GCC_GRV { get; set; }
        public virtual PER_KRM_BRM_KDR_TNM PER_KRM_BRM_KDR_TNM { get; set; }
        public virtual PER_KRM_BRM_TNM PER_KRM_BRM_TNM { get; set; }
        public virtual PER_SAKAT_TNM PER_SAKAT_TNM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_NBT_VRD_TNM> PER_NBT_VRD_TNM { get; set; }
    }
}
