//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_NBT_VRD_PER
    {
        public int VRD_NO { get; set; }
        public decimal YIL { get; set; }
        public string AY { get; set; }
        public int NBT_TTN_PER_ID { get; set; }
        public string GUN { get; set; }
        public int SIRA_NO { get; set; }
        public Nullable<int> NBT_TTCK_PER_ID { get; set; }
        public string NBT_DGS_NDN { get; set; }
        public Nullable<decimal> BSL_SAAT { get; set; }
        public Nullable<decimal> BTS_SAAT { get; set; }
    
        public virtual PER_KIMLIK PER_KIMLIK { get; set; }
        public virtual PER_KIMLIK PER_KIMLIK1 { get; set; }
        public virtual PER_NBT_VRD PER_NBT_VRD { get; set; }
    }
}
