//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_OZEL_MUAYENE
    {
        public int PER_ID { get; set; }
        public int MUAYENE_KODU { get; set; }
        public string MUAYENE_ADI { get; set; }
        public string ADR { get; set; }
        public string TLF { get; set; }
        public Nullable<System.DateTime> BSL_TRH { get; set; }
        public Nullable<System.DateTime> BTS_TRH { get; set; }
        public string FAKS { get; set; }
    
        public virtual PER_KIMLIK PER_KIMLIK { get; set; }
    }
}
