//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_KAN_ISTM_FRM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PER_KAN_ISTM_FRM()
        {
            this.PER_KAN_ISTM_FRM_TUR = new HashSet<PER_KAN_ISTM_FRM_TUR>();
        }
    
        public int KAN_ISTM_FRM_NO { get; set; }
        public string TCKIMLIK_NO { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string CINS_KODU { get; set; }
        public string TESHIS { get; set; }
        public string ONCE_TRNSFZYN_YPLD_EH { get; set; }
        public Nullable<System.DateTime> ISTM_TRH { get; set; }
        public string UNITE { get; set; }
        public string SERVIS { get; set; }
        public string HASTA_ODA_NO { get; set; }
        public string KAN_ISTM_NDN { get; set; }
        public string KAN_GRP_KODU { get; set; }
        public Nullable<System.DateTime> TRNSFZYN_TRH { get; set; }
        public Nullable<int> ISTM_YPN_DKTR_ID { get; set; }
    
        public virtual PER_KIMLIK PER_KIMLIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PER_KAN_ISTM_FRM_TUR> PER_KAN_ISTM_FRM_TUR { get; set; }
    }
}
