//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbys.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_KART_KURUM
    {
        public int KRID { get; set; }
        public string KR_ADI { get; set; }
        public string KR_ALT_ADI { get; set; }
        public string HASTANE_YONETICISI { get; set; }
    }
}
